// demo-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import 'phaser-ce/build/custom/pixi'
import * as Phaser from 'phaser-ce';

const STATES = {
  FIRST: 'FirstState',
  SECOND: 'SecondState'
}

class CommonState extends Phaser.State {
  helloWorld: Phaser.Text

  init () {
    this.stage.backgroundColor = '#24252A';
  }

  create () {
    this.helloWorld = this.add.text(
      this.game.world.centerX, 
      this.game.world.centerY, 
      "Hello World", { 
        font: "40px Arial", 
        fill: "#ffffff" 
      }
    );
    this.helloWorld.anchor.set(0.5);

    var keyC = this.game.input.keyboard.addKey(Phaser.Keyboard.C);
    keyC.onDown.add(function() {
      this.game.state.start(
        this.state.current === STATES.FIRST ?
          STATES.SECOND : STATES.FIRST
      );
    }, this);
  }

  setAngle (angle: number) {
    this.helloWorld.angle = angle;
  }
}

class FirstState extends CommonState {
  update () {
    this.helloWorld.angle += 1;
  }
}

class SecondState extends CommonState {
  update () {
    this.helloWorld.angle -= 1;
  }
}

class BootState extends Phaser.State {
  create() {
    this.state.add(STATES.FIRST, FirstState, true);
    this.state.add(STATES.SECOND, SecondState, false);

    this.state.start(STATES.FIRST);
  }
}

interface GameInstance extends Phaser.IGameConfig {
  instance: Phaser.Game
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  initialize = false
  game: GameInstance = {
    width: "100%",
    height: "100%",
    renderer: Phaser.AUTO,
    scaleMode: Phaser.ScaleManager.EXACT_FIT,
    state: BootState,
    instance: null
  }

  getInstance () {
    return this.game.instance;
  }

  initializeGame () {
    this.initialize = true;
  }

  changeAngle () {
    const instance = this.getInstance();
    const currentState = instance.state.getCurrentState() as CommonState;
    currentState.helloWorld.angle = 0;
  }
}

<div class="App">
  <header class="App-header">
    <ng-container *ngIf="!initialize">
      <img src="../assets/logo.png" class="App-logo" alt="logo" />
      <div (click)="initializeGame()" class="flex">
        <a href="javascript:void(0)" class="bttn">Initialize</a>
      </div>
    </ng-container>
    <ion-phaser-ce [game]="game" [initialize]="initialize"></ion-phaser-ce>
    <div *ngIf="initialize" (click)="changeAngle()" class="flex bottom-button">
      <a href="javascript:void(0)" class="bttn">Set Angle</a>
    </div>
  </header>
</div>

// demo-react/src/App.js
/**
 * @flow
 */

import React, { Component } from 'react'
import { IonPhaser } from '@ion-phaser-ce/react'
import Phaser from 'phaser-ce'
import logo from './assets/logo.png'

import './App.css'

class App extends Component {

  state = {
    unmounted: false,
    initialize: false,
    game: {
      width: "100%",
      height: "100%",
      renderer: Phaser.AUTO,
      state: {
        init: function() {
          this.stage.backgroundColor = '#24252A';
        },
        create: function() {
          this.helloWorld = this.game.add.text(
            this.game.world.centerX, 
            this.game.world.centerY, 
            "Hello World", { 
              font: "40px Arial", 
              fill: "#ffffff" 
            }
          );
          this.helloWorld.anchor.set(0.5);
        },
        update: function() {
          this.helloWorld.angle += 1;
        }
      }
    }
  }

  initializeGame = () => {
    this.setState({ initialize: true })
  }

  destroy = () => {
    this.setState({ unmounted: true })
  }

  render() {
    const { initialize, game, unmounted } = this.state
    return (
      <div className="App">
        <header className="App-header">
          { !initialize &&
            <React.Fragment>
              <img src={logo} className="App-logo" alt="logo" />
              <div onClick={this.initializeGame} className="flex">
                <a href="#1" className="bttn">Initialize</a>
              </div>
            </React.Fragment>
          }
          { !unmounted && <IonPhaser class="game" game={game} initialize={initialize} /> }
          { initialize && !unmounted &&
            <div onClick={this.destroy} className="flex destroyButton">
              <a href="#1" className="bttn">Destroy</a>
            </div>
          }
        </header>
      </div>
    );
  }
}

export default App;
